version: '3'

services:
  next-app:
    container_name: next-app
    build:
      dockerfile: Dockerfile.dev

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./next.config.js:/app/.next.config.js
      - ./styles:/app/styles
      - ./tailwind.config.js:/app/tailwind.config.js
    ports:
      - 3002:3000
